logger:
  level: DEBUG
  format: logfmt
  add_timestamp: true

input:
  kafka_franz:
    seed_brokers:
      - localhost:9092
    topics:
      - github_events
    consumer_group: github_events
    auto_replay_nacks: true
    batching:
      count: 100
      period: 100ms

pipeline:
  processors:
    # Ignore pushes and creates for now
    - mapping: |
        if this.type == "PushEvent" {
              root = deleted()
        }
        if this.type == "CreateEvent" {
              root = deleted()
        }

output:
  opensearch:
    urls:
      - https://localhost:9200
    tls:
      enabled: true
      skip_cert_verify: true
    index: github_events
    action: index
    id: '${! json("id") }'
    basic_auth:
      enabled: true
      username: elastic
      password: elastic
